// Generated by https://quicktype.io

export interface LoginResponse {
    id:       number;
    nombre:   string;
    apellido: string;
    login:    string;
    clave:    string;
    correo:   string;
    telefono: string;
}
// Generated by https://quicktype.io

export interface EntrevistasResponse {
    id:                   number;
    createAt:             string;
    perfilBuscado:        string;
    comentariosPrueba:    string;
    comentariosGenerales: string;
    recomendaciones:      string;
    descripcionPersonal:  string;
    preguntasCandidato:   string;
}
// Generated by https://quicktype.io

export interface PreguntasResponse {
    id:      number;
    detalle: string;
    activo:  boolean;
}
