// Generated by https://quicktype.io

export interface LoginResponse {
    id:       number;
    nombre:   string;
    apellido: string;
    login:    string;
    clave:    string;
    correo:   string;
    telefono: string;
}
